jaspreet338/tech-pandas-STAR

- client/src/pages/Home.css
- client/src/pages/Home.js
- client/src/pages/Navbar.js
- client/src/pages/SingleStar.js
- client/src/pages/StarList.js
i have created list star on dasboard with dummy data
#4 
Fixes #1
> #4-list-all-star-jaspreet_kaur

- server/api.js
- server/app.js
- server/db.js
- server/starAPI.js
- server/starDatabase.sql
> Issue#5 -Mesgna -Woldeab

- server/starDatabase.sql
> 3 - database star created - Mesgna

- client/src/App.js
- client/src/pages/Dashboard.js
- client/src/pages/Home.js
Created an empty Dashboard page 
Implements #6 
- [] I have commented my code
- [] I have updated any documentation
> #6-Empty Dashboard page - Tsione

- render.yaml
> change render web name

- server/db.js
remove bug mac problem
Fixes #1
> mac converts localhost to 127.0.0.1.-Fatemeh

- server/controllers/auth.controller.js
- server/model/user.model.js
Registeration-api is created for ticket. It contains forms that clients can enter their details. 
Fixes #1
> #Issue7 - registration-api - Fatemeh Rahimi

- server/model/user.model.js
Fixed some forgotten codes.
Implement #7 
- [ x] My code follows the style guidelines of this project
- [ x] I have carefully reviewed my own code
> Registration-api- Tsione

- client/src/pages/AddForm.js
- client/src/pages/SingleStar.js
issue #3 star from mesgna woldeab
created a form where users can add their stars. I also used posted method to send request to the server.
Fixes #1
> Issue #3 Add star from / mesgna -woldeab

- README.md
Add to 'Deploy to Render' button  an correct link address .
Fixes #1
> Issue25-fix-readme-bug-Fatemeh

- client/src/App.js
- client/src/pages/EditForm.js
- client/src/pages/SingleStar.js
- client/src/pages/StarList.js
#18-Edit-star-form-jaspreet_kaur
i create new component to create edit form and also make another branch
#18 
Fixes #1
- [ x  ] My code follows the style guidelines of this project
- [ x  ] I have carefully reviewed my own code
> Editform#18

- client/src/pages/Navbar.js
- client/src/pages/SingleStar.js
> Added card on single stars using react-bootstrap

- client/src/pages/Navbar.js
>  Nav-Bar designed using css bootstrap issue #21

- client/src/App.js
- client/src/pages/RegisterForm.js
finish ready for review
#57 
Fixes #57 
- [ x  ] My code follows the style guidelines of this project
- [  ] I have commented my code
- [  ] I have updated any documentation
> #57-redirect-login-to-Registration-jaspreet_kaur

- client/src/pages/SingleStar.js
- server/model/user.model.js
>  SingleStar conflict resolved

- client/src/App.js
- client/src/pages/Dashboard.js
- client/src/pages/RegisterForm.js
- server/api.js
- server/controllers/auth.controller.js
- server/starAPI.js
- server/userAPI.js
finished the ticket and it is ready for review
#53 
Fixes #53 
- [ x  ] My code follows the style guidelines of this project
- [ x ] I have commented my code
- [ x ] I have updated any documentation
> #53staff dashboard

- client/src/App.js
- client/src/pages/RegisterForm.js
- server/api.js
- server/model/user.model.js
sorting minor issues so the pages link together properly.
#75 
Fixes #75 
> #75-debug-minor-issues-jaspreet_kaur

- client/src/pages/RegisterForm.js
added css
#75 
Fixes #75 
- [   ] I have commented my code
> #75/debug-minor-issues-jaspreet_kaur

- client/src/pages/RegisterForm.js
fixed the registration css because of some issues
#21 
Fixes #21 
> 21-fixed-css

- client/src/pages/Component/DeleteBtn.js
Fixed a bug by removing "setStars(star);" friom line 19
Fixes #80
- [x ] My code follows the style guidelines of this project
- [x ] I have carefully reviewed my own code
- [ x] I have updated any documentation
> #80-Fix-delete-btn-Tsione

- client/src/pages/Search.js
App is crashing as the search component is being imported from './Search' but the file has been created as search.js
Fix by renaming this file to Search.js
Fixes #1
> rename component file to start with a capital

- client/src/pages/Registration.css
- package-lock.json
- package.json
Additional fixes needed
Fixes #1
> Chore fix build error-jaspreet_kaur

- package-lock.json
> updated lock file-jaspreet_kaur

- server/utils/middleware.js
current authentication did not aalow web pages to be served.
Fixes #1
> allow web pagespast authontication-fatemeh

- client/src/pages/Navbar.js
- client/src/pages/RegisterForm.js
- client/src/pages/Registration.css
- server/api.js
- server/authAPI.js
added image, colours and style the page
#108 
Fixes #108 
> 108-Styling-register-form-jaspreet_kaur

- server/starAPI.js
- server/starDatabase.sql
created database and added API for comments from TA's or mentors
#71 
Fixes #71 
> #71/comments-for-stars-jaspreet_kaur/Mesgna

- client/src/pages/Dashboard.js
- client/src/pages/SingleStar.js
- client/src/pages/StarList.js
> 102#-Change-dashboard-view-Tsione

- client/src/App.js
- client/src/pages/CommentList.js
- client/src/pages/Component/AddComment.js
- client/src/pages/Component/DeleteComment.js
- client/src/pages/Component/EditComment.js
- client/src/pages/SingleComment.js
- client/src/pages/SingleStar.js
- client/src/pages/SingleStarView.js
- client/src/pages/StarList.js
- server/starAPI.js
Adding Add, Edit and Delete buttons and functionality for the comments
Implement #88
> 88~delete-edit-add-Fatemah&Tsione

- client/src/pages/Search.js
- client/src/pages/StarList.js
>  search updated

- client/src/App.js
- client/src/index.html
- client/src/pages/About.css
- client/src/pages/About.js
- client/src/pages/Home.css
- client/src/pages/RegisterForm.js
- client/src/pages/Registration.css
created about page and added css
#106 
Fixes #106 
> 106/about-page-content -and- style- jaspreet&tsione

- server/starAPI.js
>  Post for stars and comments amended to take user_id rather random id

- client/src/pages/SingleStar.js
- client/src/pages/SingleStarView.js
i have changed the creator name to appear only when is logged as TA or Mentor
Fixes #1
>  updating creator name to appear only logged as ta or mentor

- server/starAPI.js
>  added favourite boolen to the star api

- client/src/pages/Component/Dashboard.css
> Added position:relative

- client/src/pages/Home.css
> Final-tweaks-polish-Tsione
